Update macos.yml

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -36,8 +36,12 @@ jobs:
         run: |
           ytloc=$(which yt-dlp)
           output=$(mpv --script-opts="ytdl_hook-ytdl_path=$ytloc,youtube-upnext-auto_add=no,youtube-upnext-fetch_on_start=yes" --scripts=youtube-upnext.lua --msg-level=youtube_upnext=trace "https://www.youtube.com/watch?v=VpOLXXBcAl0" 2>&1)
+          echo $output
           if [[ $output == *"wget and json decode succeeded"* ]]; then
-            echo "It's there!"
+            exit 0
+          else
+            echo "Not found: wget and json decode succeeded"
+            exit 1
           fi
 
 
